![This is an image](Quant-Trading.jpg)

<font size="3">
Please visit our website <a href="https://www.quant-trading.co" target="_blank">quant-trading.co</a> for more tools on quantitative finance and data science.
</font>

# **MARKET EFFICIENCY TEST WITH PYTHON**

## **How to run a market efficiency test using python code**

<font size="3"> In this post we are going to explain a simple market efficiency test with python. This test is used by practitioners to assess how inefficient a market is. Through history people have developed multiple tests for this purpose. The test we are going to show was not design specifically to prove if a market was efficient or not. However, the idea on which it is based, helps to illustrate this concept quite well. Hence its usefulness. This test was developed by Louis Bachelier during the previous century. Its main goal is to quantify the probability of a run of certain number of positive or negative returns. If you have 5 days of positive returns, without a single negative one, then you have a positive run of 5 observations. <br><br>
Longer runs are less probable in an efficient market. This has to do with something called positive serial autocorrelation. Efficient markets don’t exhibit positive serial autocorrelation, which means that you can’t find long positive or negative runs. Momentum trader wouldn’t be able to make any extraordinary profits in those markets. 
<br><br>

In [1]:
import warnings
warnings.filterwarnings('ignore')

from datetime import datetime
import numpy as np
import pandas as pd
from scipy.stats import norm

## **Import the data**

<font size="3"> We can use this <a href="https://github.com/dhonn/schwab-python-api/" target="_blank">csv file</a> that contains the prices for the netflix stock to run the example. Alternatively, you can download the data from the Yahoo Finance API. If you would like to know how to do that, please check the following <a href="https://quant-trading.co/how-to-download-data-from-yahoo-finance-api/" target="_blank">blog post</a>. If you would like to know how to download data from public APIs such as this from Yahoo Finance, or others like SEC EDGAR, FINRA, OECD among others, we recommend you to look at our course <a href="https://quant-trading.co/cursos/data-science-for-trading/" target="_blank">"Data Science for Investing and Trading".</a> 
<br><br>

In [2]:
#IMPORT EQUITY PRICES
df = pd.read_csv('NFLX.csv',encoding='UTF-8')   #IN THIS EXAMPLE WE USE NETFLIX STOCK

## **Calculate daily returns**

<font size="3"> We can calculate the returns simply as the quotient between today's price and yesterday's price minus one. We can also assign the character X to the column runs.
<br><br>

In [3]:
#CALCULATE DAILY RETURNS
df['daily_return'] = df['Close'][1:].values/ df['Close'][:-1]-1
df['runs'] = "X"
df

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,daily_return,runs
0,2002-05-23,1.156429,1.242857,1.145714,1.196429,104790000,0,0.0,0.011343,X
1,2002-05-24,1.214286,1.225000,1.197143,1.210000,11104800,0,0.0,-0.043684,X
2,2002-05-28,1.213571,1.232143,1.157143,1.157143,6609400,0,0.0,-0.046297,X
3,2002-05-29,1.164286,1.164286,1.085714,1.103571,6757800,0,0.0,-0.029125,X
4,2002-05-30,1.107857,1.107857,1.071429,1.071429,10154200,0,0.0,0.004667,X
...,...,...,...,...,...,...,...,...,...,...
5008,2022-04-13,343.920013,352.000000,341.160004,350.429993,3231000,0,0.0,-0.026539,X
5009,2022-04-14,350.950012,352.000000,339.859985,341.130005,4338100,0,0.0,-0.009586,X
5010,2022-04-18,340.000000,342.359985,331.619995,337.859985,5105000,0,0.0,0.031818,X
5011,2022-04-19,333.220001,351.679993,333.220001,348.609985,20906900,0,0.0,-0.351166,X
5012,2022-04-20,245.199997,248.449997,212.509995,226.190002,132759913,0,0.0,NaN,X

## **Calculate positive and negative runs**

<font size="3"> A run is a sequence of positive or negative returns. If you have 5 days of positive returns, without a single negative one, then you have a positive run of 5 observations. The run test if a very useful market efficiency test. To calculate these runs we need to track if the return is positive or negative. We do that using the numpy function "sign". For the first observation we initialize the runs writting P1 for the first positive run or N1 for the first negative run. Then we loop throughout the DataFrame. You can observe the script below. 
<br><br>

In [4]:
#THIS IS A SCRIPT TO CALCULATE POSITIVE AND NEGATIVE RUNS
if np.sign(df['daily_return'].iloc[0]) == 1:
    df['runs'].iloc[0] = "P1"
    positive_run = 1
    negative_run = 0
    positive_returns = 1
    negative_returns = 0
    
else:
    df['runs'].iloc[0] = "N1"
    positive_run = 0
    negative_run = 1
    positive_returns = 0
    negative_returns = 1


for i in range(0,df.shape[0]-1):
    
    if np.sign(df['daily_return'].iloc[i+1]) == 1:
        positive_returns = positive_returns + 1
        
        if df['runs'].iloc[i][:1] == "P":
            df['runs'].iloc[i+1] = "P" + str(positive_run)
        else:
            positive_run = positive_run + 1
            df['runs'].iloc[i+1] = "P" + str(positive_run)
        
    else:
    
        negative_returns = negative_returns + 1
        
        if df['runs'].iloc[i][:1] == "N":
            df['runs'].iloc[i+1] = "N" + str(negative_run)
        else:
            negative_run = negative_run + 1
            df['runs'].iloc[i+1] = "N" + str(negative_run)
        
   
       
print("Positive returns P = " + str(positive_returns))
print("Negative returns N = " + str(negative_returns))
print("Runs U = " + str(positive_run + negative_run))

Positive returns P = 2529
Negative returns N = 2484
Runs U = 2562

In [5]:
#DATAFRAME FOR VISUAL INSPECTION
df

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,daily_return,runs
0,2002-05-23,1.156429,1.242857,1.145714,1.196429,104790000,0,0.0,0.011343,P1
1,2002-05-24,1.214286,1.225000,1.197143,1.210000,11104800,0,0.0,-0.043684,N1
2,2002-05-28,1.213571,1.232143,1.157143,1.157143,6609400,0,0.0,-0.046297,N1
3,2002-05-29,1.164286,1.164286,1.085714,1.103571,6757800,0,0.0,-0.029125,N1
4,2002-05-30,1.107857,1.107857,1.071429,1.071429,10154200,0,0.0,0.004667,P2
...,...,...,...,...,...,...,...,...,...,...
5008,2022-04-13,343.920013,352.000000,341.160004,350.429993,3231000,0,0.0,-0.026539,N1280
5009,2022-04-14,350.950012,352.000000,339.859985,341.130005,4338100,0,0.0,-0.009586,N1280
5010,2022-04-18,340.000000,342.359985,331.619995,337.859985,5105000,0,0.0,0.031818,P1281
5011,2022-04-19,333.220001,351.679993,333.220001,348.609985,20906900,0,0.0,-0.351166,N1281
5012,2022-04-20,245.199997,248.449997,212.509995,226.190002,132759913,0,0.0,NaN,N1281

## **Statistical test**

<font size="3"> We can define the quantity x as the expected number of runs, while s is its standard deviation. x should have a normal distribution. Hence, we can try a statistical test to see if it falls within a specific confidence interval. We can formulate the null hypothesis as: 1 day returns are random. To see if we can reject the null hypothesis, we can use the Z statistic which can be easily calculated using x, s and u, where the latter corresponds to the number of runs in our sample. This is the way to perform a market efficiency test with python. <br><br> 
If we set the significance level at 5%, we cannot reject the null hypothesis. To calculate the Z-score we use the function norm p.p.f . This function is in the package scipy. We explained this test with more detail in our course on <a href="https://quant-trading.co/cursos/trading-algoritmico-2/" target="_blank">Algorithmic Trading.</a>. There we also explain how to build momentum and mean reversion trading models. Please take a look if you are interested. 
<br><br>

In [6]:
x = (2*positive_returns*negative_returns/(positive_returns+negative_returns))+1
s = np.sqrt((2*positive_returns*negative_returns*(2*positive_returns*negative_returns-(positive_returns+negative_returns)))/((positive_returns+negative_returns)**2*((positive_returns+negative_returns)-1)))
u = positive_run + negative_run
Z = (u - x - 0.5)/ s
ABSZ = np.abs(Z)

In [7]:
alfa = 0.05
score = norm.ppf(1-alfa/2, )

if ABSZ > score:
    print("We can reject the null hypothesis which states that returns are random")
else:
    print("We can not reject the null hypothesis which states that returns are random")

We can not reject the null hypothesis which states that returns are random

<font size="3"> If this content is helpful and you want to make a donation please click on the button

[![paypal](https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=29CVY97MEQ9BY)